export const customerThemes = [
  {
    id: "classic",
    name: "کلاسیک",
    description: "طراحی سنتی و گرم",
    preview: "/placeholder.svg?height=200&width=300&text=Classic+Theme",
    colors: {
      primary: "#8B4513",
      secondary: "#D2691E",
      background: "from-amber-50 to-orange-100",
      card: "bg-white",
      text: "text-gray-900",
    },
  },
  {
    id: "modern",
    name: "مدرن",
    description: "طراحی مینیمال و شیک",
    preview: "/placeholder.svg?height=200&width=300&text=Modern+Theme",
    colors: {
      primary: "#2563eb",
      secondary: "#1d4ed8",
      background: "from-slate-50 to-blue-100",
      card: "bg-white/80 backdrop-blur-sm",
      text: "text-slate-900",
    },
  },
  {
    id: "elegant",
    name: "شیک",
    description: "طراحی لوکس و اشرافی",
    preview: "/placeholder.svg?height=200&width=300&text=Elegant+Theme",
    colors: {
      primary: "#7c3aed",
      secondary: "#5b21b6",
      background: "from-purple-50 to-indigo-100",
      card: "bg-white/90 backdrop-blur-md",
      text: "text-purple-900",
    },
  },
  {
    id: "nature",
    name: "طبیعی",
    description: "طراحی سبز و طبیعی",
    preview: "/placeholder.svg?height=200&width=300&text=Nature+Theme",
    colors: {
      primary: "#059669",
      secondary: "#047857",
      background: "from-green-50 to-emerald-100",
      card: "bg-white/85",
      text: "text-green-900",
    },
  },
  {
    id: "dark",
    name: "تیره",
    description: "طراحی مدرن و تیره",
    preview: "/placeholder.svg?height=200&width=300&text=Dark+Theme",
    colors: {
      primary: "#f59e0b",
      secondary: "#d97706",
      background: "from-gray-900 to-gray-800",
      card: "bg-gray-800/80 backdrop-blur-sm",
      text: "text-white",
    },
  },
  {
    id: "warm",
    name: "گرم",
    description: "طراحی گرم و دوستانه",
    preview: "/placeholder.svg?height=200&width=300&text=Warm+Theme",
    colors: {
      primary: "#dc2626",
      secondary: "#b91c1c",
      background: "from-red-50 to-pink-100",
      card: "bg-white/90",
      text: "text-red-900",
    },
  },
  {
    id: "3d-luxury",
    name: "سه‌بعدی لوکس",
    description: "طراحی سه‌بعدی مدرن با افکت‌های شیک",
    preview: "/placeholder.svg?height=200&width=300&text=3D+Luxury+Theme",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      background: "from-slate-900 via-purple-900 to-slate-900",
      card: "bg-white/10 backdrop-blur-xl border border-white/20",
      text: "text-white",
    },
  },
];
